name: Add Action
on:
 push:
   branches:
     - main
jobs:
 Cypress-Test:
   runs-on: ubuntu-latest
   steps:
     - name: Checkout GitCode
       uses: actions/checkout@v2
     - name: Cypress.io
       uses: cypress-io/github-action@v6.5.0
       with:
         browser: chrome
         command: npx cypress run
         
